from __future__ import annotations
from enum import Enum
from pydantic import BaseModel, Field


class IntentType(str, Enum):
    """Intent classification produced by the IntentRouter."""

    FILESYSTEM = "filesystem"
    TERMINAL = "terminal"
    GIT = "git"
    SEARCH = "search"
    WEB = "web"
    MCP = "mcp"
    SEMANTIC = "semantic"
    REASONING = "reasoning"
    AMBIGUOUS = "ambiguous"


class PipelineType(str, Enum):
    """Execution pipeline."""

    DETERMINISTIC = "deterministic"
    SEMANTIC = "semantic"
    REASONING = "reasoning"


class RuntimeRequest(BaseModel):
    """Request entering the Runtime."""

    prompt: str


class RuntimeResponse(BaseModel):
    """Response returned by the Runtime."""

    content: str


class IntentResult(BaseModel):
    """Output from the Intent Router."""

    intent: IntentType

    pipeline: PipelineType | None = None

    tool_name: str | None = None

    confidence: float = Field(
        ge=0.0,
        le=1.0,
    )


class ResourceState(BaseModel):
    """Current runtime resource state."""

    provider: str

    model: str

    context_window: int

    quantization: str | None = None

    estimated_ram_mb: int | None = None

    supports_streaming: bool = True

    supports_tools: bool = True

    supports_grammar: bool = False


class RuntimeContext(BaseModel):
    """Context passed through Runtime execution."""

    request: RuntimeRequest

    intent: IntentResult

    resources: ResourceState


class PromptContext(BaseModel):
    """Prompt generated by PromptManager."""

    system_prompt: str

    user_prompt: str


class GrammarContext(BaseModel):
    """Grammar configuration."""

    enabled: bool = False

    grammar: str | None = None